"""key for model's input_shapes dict"""
# todo 키를 등록하고 접근해주는 클래스를 만들어야하나?
INPUT_SHAPE_KEY_DATA_X = "INPUT_SHAPE_KEY_DATA_X"
INPUT_SHAPE_KEY_LABEL = "INPUT_SHAPE_KEY_LABEL"
INPUT_SHAPE_KEY_LABEL_SIZE = "INPUT_SHAPE_KEY_LABEL_SIZE"

INPUT_SHAPE_KEY_TEST_DATA_X = "INPUT_SHAPE_KEY_TEST_DATA_X"
INPUT_SHAPE_KEY_TEST_LABEL = "INPUT_SHAPE_KEY_TEST_LABEL"
