"""key for model's input_shapes dict"""
INPUT_SHAPE_KEY_DATA_X = "INPUT_SHAPE_KEY_DATA_X"
INPUT_SHAPE_KEY_LABEL = "INPUT_SHAPE_KEY_LABEL"
INPUT_SHAPE_KEY_LABEL_SIZE = "INPUT_SHAPE_KEY_LABEL_SIZE"
INPUT_SHAPE_KEY_TEST_DATA_X = "INPUT_SHAPE_KEY_TEST_DATA_X"
INPUT_SHAPE_KEY_TEST_LABEL = "INPUT_SHAPE_KEY_TEST_LABEL"

ISK_X = "ISK_X"
ISK_TRAIN_X = "ISK_TRAIN_X"
ISK_TRAIN_LABEL = "ISK_TRAIN_LABEL"
ISK_TEST_X = "ISK_TEST_X"
ISK_TEST_LABEL = "ISK_TEST_LABEL"

